name: Unit Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  unitTest:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Unit tests
        run: |
          bash ./gradlew test
